apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rnk
  name: sa-secret-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: sa-secret-reader
  namespace: rnk
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: sare-sect-rolebinding # "name" is case sensitive
  namespace: rnk
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: sa-secret-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io